kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-gcp-maskinporten-client-api
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
  azure:
    sidecar:
      enabled: true
      autoLogin: true
    application:
      enabled: true
      allowAllUsers: false
      claims:
        groups:
          - id: "7ef907b4-ec9f-47dd-ab41-4e54ba32ceb1" #AAD pensjonopptjening testgruppe
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: nav:pensjonopptjening:ekstern.afp.beholdningsgrunnlag.beregn.read
        - name: nav:pensjonopptjening:ekstern.afp.beholdningsgrunnlag.simuler.read
  accessPolicy:
    outbound:
      rules:
        - application: 'logging'
          namespace: 'nais-system'

  ingresses:
    - https://pensjon-opptjening-gcp-maskinporten-client-api.intern.dev.nav.no
  image: {{ image }}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 50
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 50
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
