name: 'check-deploy-to-prod-approved'

on:
  workflow_run:
    workflows:
      - 'Release new version'
    types:
      - 'completed'

jobs:
  check-workflow-approved:
    name: 'Check workflow approved'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Extract workflow info'
        id: extract-workflow-info
        run: |
          response=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{env.REPO}}/actions/runs/${{env.ID}}/approvals)
          
          skipped=$(jq 'any(.state == "skipped")' <<< $response)
          self_approved=$(jq 'map(select(.state == "approved")) | map(.user.html_url) | any(. == "${{env.ACTOR_URL}}")' <<< $response)
          
          if $skipped || $self_approved;
            then
              echo "send_slack_alert=true" >> $GITHUB_OUTPUT
            else
              echo "send_slack_alert=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          REPO: '${{ github.repository }}'
          ID: '${{ github.event.workflow_run.id }}'
          ACTOR_URL: '${{ github.event.workflow_run.actor.html_url }}'

      - name: 'Download run info from previous workflow'
        run: |
          echo "Fetching artifacts for run ID: $RUN_ID"
          ARTIFACT_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts \
            | jq -r '.artifacts [] | select(.name=="release-info") | .id')
          echo "ARTIFACT_ID=$ARTIFACT_ID"
          curl -L -H "Authorization: Bearer $GH_TOKEN" \
          -o release-info.zip \
          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip
          echo "Unzipping:"
          unzip release-info.zip -d .
        env:
          GH_TOKEN: ${{ github.token }}
          RUN_ID: ${{ github.event.workflow_run.id }}

      - name: 'Read release info'
        id: title
        run: |
          title=$(cat release_info.txt)
          echo "release_title=$title" >> $GITHUB_OUTPUT

      - name: 'Send Slack message if deploy approval is buypassed or self-approved'
        id: invoke-slack-webhook
        uses: slackapi/slack-github-action@v2.1.1
        if: ${{ steps.extract-workflow-info.outputs.send_slack_alert == 'true' }}
        with:
          webhook: ${{ secrets.SLACK_WORKFLOW_APPROVAL_BUYPASS_WEBHOOK }}
          webhook-type: webhook-trigger
          payload: |
            github_user_url: "${{ github.event.workflow_run.actor.html_url }}"
            workflow_url: "${{ github.event.workflow_run.html_url }}"
            workflow_title: "${{ steps.title.outputs.release_title }}"