name: Bygg og deploy pensjon-opptjening-gcp-maskinporten-client-api til dev-gcp

on:
  workflow_dispatch:

jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: ./pensjon-opptjening-gcp-maskinporten-client-api
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v5

      - name: 'Java 21'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 'Setup Gradle'
        uses: gradle/actions/setup-gradle@v5

      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@v5

      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date '+%Y-%m-%d--%H-%M-%S')" >> $GITHUB_ENV
          echo "GIT_COMMIT=$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_ENV
          echo "GIT_BRANCH=$(echo ${{github.ref_name}})" >> $GITHUB_ENV

      - name: 'Configure git reference tag'
        run: |
          echo "GIT_REF_TAG=git_${GIT_BRANCH}_${GIT_COMMIT}" >> $GITHUB_ENV

      - name: 'Build application'
        run: |
          ../gradlew build

      - name: 'Information'
        run: |
          echo "PWD=$PWD"
          ls -l Dockerfile

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          dockerfile: pensjon-opptjening-gcp-maskinporten-client-api/Dockerfile
          tag: ${{ env.GIT_REF_TAG }}

      - name: 'Deploy pensjon-opptjening-gcp-maskinporten-client-api to dev-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: pensjon-opptjening-gcp-maskinporten-client-api/nais-dev.yml
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}