name: Bygg og deploy pensjon-opptjening-gcp-maskinporten-client-api til dev-gcp

on:
  workflow_dispatch:

jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        working-directory: ./pensjon-opptjening-gcp-maskinporten-client-api
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 'Build application'
        run: |
          ./gradlew build

      - name: 'Information'
        run: |
          echo "PWD=$PWD"
          ls -l Dockerfile

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          dockerfile: ./Dockerfile

      - name: 'Deploy pensjon-opptjening-gcp-maskinporten-client-api to dev-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: pensjon-opptjening-gcp-maskinporten-client-api/nais-dev.yml
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}