name: Monitor dependencies with Dependabot
on:
  schedule:
    - cron: '25 8,13 * * 1,2,3,4,5'
    - cron: '25 13 * * 0,6'
jobs:
  dependabot:
    name: 'Monitor dependencies with Dependabot'
    runs-on: ubuntu-24.03
    permissions:
      contents: write
    steps:

      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          java-version: 21
          cache: 'gradle'
          distribution: 'temurin'

      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Run snapshot action'
        uses: mikepenz/gradle-dependency-submission@v1
        with:
          fail-on-error: true
          gradle-dependency-path: "build.gradle.kts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
