name: 'Release new version'


on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    environment: release
    defaults:
      run:
        working-directory: ./pensjon-opptjening-gcp-maskinporten-client
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Java 21'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: 'Setup git'
        run: git config user.email "${{ github.actor }}@users.noreply.github.com" && git config user.name "Github Actions"

      - name: 'Capture version number for release'
        run: echo "VERSION=$(grep -v '^#' gradle.properties | grep 'version=' | cut -d '=' -f2 | xargs)" >> $GITHUB_ENV

      - name: 'Build and update version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build release -Prelease.useAutomaticVersion=true

      - name: 'Check out release-version'
        uses: actions/checkout@v4
        with:
          ref: "release-${{ env.VERSION }}"

      - name: 'Publish package'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Generate release info'
        run: |
          echo "Releaset ${{env.COMMIT}} som ${{ env.VERSION }}" > release_info.txt

      - name: 'Upload release info'
        uses: actions/upload-artifact@v4
        with:
          name: release-info
          path: release_info.txt
